language: node_js

env:
 - IMAGE_NAME=341526889944.dkr.ecr.eu-west-1.amazonaws.com/travis:1.0-$TRAVIS_BUILD_NUMBER
services:
  - docker

script:
  - npm install

after_success:
  - pip install --user awscli 
  - eval $(aws ecr get-login --region eu-west-1 --no-include-email)
  - docker build -t 3r1co/nodetest .
  - docker tag 3r1co/nodetest $IMAGE_NAME
  - docker push $IMAGE_NAME
#  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameter-override ImageName=$IMAGE_NAME
#  - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ecs-deployment --region eu-west-1 --parameters "ParameterKey=ImageName,ParameterValue=$IMAGE_NAME"
  - sh ./install.sh
  - cat deploy.yaml | envsubst > kubernetes.yaml
  - kubectl apply -f kubernetes.yaml
