apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:
    server: "42"
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: tureves
    username: undeuxtrois

